name: Convert JSON to SRS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Convert JSON to SRS
      run: |
        for file in rules/*.json; do
          filename=$(basename "$file" .json)
          echo "Processing $filename.json"
          
          # Read JSON content
          json_content=$(cat "$file")
          
          # Extract values using jq (you can customize this based on your JSON structure)
          name=$(echo "$json_content" | jq -r '.name // "Unknown"')
          type=$(echo "$json_content" | jq -r '.type // "Unknown"')
          
          # Create SRS content
          srs_content="SRS Name: $name\nType: $type"
          
          # Write to a new .srs file
          echo -e "$srs_content" > "rules/$filename.srs"
          
          echo "Generated $filename.srs"
        done

    - name: Commit SRS files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add rules/*.srs
        git commit -m "Add generated SRS files"
        git push
